/*
 * This source file was generated by the Gradle 'init' task
 */
package helloworkflow;

import java.util.Map;

import helloworkflow.common.Utils;
import helloworkflow.workflowInterfaces.SayHelloWorkflow;
import io.temporal.client.WorkflowClient;
import io.temporal.client.WorkflowOptions;
import io.temporal.serviceclient.WorkflowServiceStubs;
import io.temporal.serviceclient.WorkflowServiceStubsOptions;

public class Starter {

    public static void main(String[] args) {
        Map<String, Object> options = Utils.parseArgs(args);
        boolean shouldFail = (boolean) options.getOrDefault("shouldFail", false);
        String target = resolveTemporalTarget();
        WorkflowServiceStubs service = WorkflowServiceStubs.newServiceStubs(
                WorkflowServiceStubsOptions.newBuilder()
                        .setTarget(target)
                        .build());
        WorkflowClient client = WorkflowClient.newInstance(service);

        SayHelloWorkflow workflow = client.newWorkflowStub(
                SayHelloWorkflow.class,
                WorkflowOptions.newBuilder()
                        .setTaskQueue("my-task-queue")
                        .setWorkflowId("say-hello-workflow")
                        .build());

        try {
            // synchronous workflow execution
            String result = workflow.sayHello("Trung Vo", shouldFail);
            System.out.println("Workflow result: " + result);
        }
        finally {
            System.out.println("Shutting down Temporal service...");
            service.shutdown();
            service.awaitTermination(10, java.util.concurrent.TimeUnit.SECONDS);
        }
    }

    static String resolveTemporalTarget() {
        return System.getProperty("temporalTarget");
    }

}
