/*
 * This source file was generated by the Gradle 'init' task
 */
package helloworkflow;

import helloworkflow.workflowInterfaces.SayHelloWorkflow;
import io.temporal.client.WorkflowClient;
import io.temporal.client.WorkflowOptions;
import io.temporal.serviceclient.WorkflowServiceStubs;
import io.temporal.serviceclient.WorkflowServiceStubsOptions;

import java.util.Map;
import java.util.UUID;

public class Starter {

    public static void main(String[] args) {
        String target = resolveTemporalTarget(System.getenv());
        WorkflowServiceStubs service = WorkflowServiceStubs.newServiceStubs(
                WorkflowServiceStubsOptions.newBuilder()
                        .setTarget(target)
                        .build());
        WorkflowClient client = WorkflowClient.newInstance(service);

        SayHelloWorkflow workflow = client.newWorkflowStub(
                SayHelloWorkflow.class,
                WorkflowOptions.newBuilder()
                        .setTaskQueue("my-task-queue")
                        .setWorkflowId(newWorkflowId())
                        .build());

        String result = workflow.sayHello("Temporal");
        System.out.println("Workflow result: " + result);

        service.shutdown();
        service.awaitTermination(10, java.util.concurrent.TimeUnit.SECONDS);
    }

    static String resolveTemporalTarget(Map<String, String> environment) {
        return System.getProperty(
                "temporal.target",
                environment.getOrDefault("TEMPORAL_ADDRESS", "127.0.0.1:7234"));
    }

    static String newWorkflowId() {
        return "say-hello-workflow-" + UUID.randomUUID();
    }
}
