/*
 * This source file was generated by the Gradle 'init' task
 */
package helloworkflow;

import java.util.Map;
import java.util.concurrent.CompletableFuture;
import java.util.concurrent.CountDownLatch;

import helloworkflow.common.Utils;
import helloworkflow.common.models.SayHelloRequest;
import helloworkflow.workflowInterfaces.SayHelloWorkflow;
import io.temporal.api.common.v1.WorkflowExecution;
import io.temporal.client.WorkflowClient;
import io.temporal.client.WorkflowOptions;
import io.temporal.client.WorkflowStub;
import io.temporal.serviceclient.WorkflowServiceStubs;
import io.temporal.serviceclient.WorkflowServiceStubsOptions;

public class Starter {

    public static void main(String[] args) {
        Map<String, Object> options = Utils.parseArgs(args);
        boolean shouldFail = (boolean) options.getOrDefault("shouldFail", false);
        String target = resolveTemporalTarget();
        WorkflowServiceStubs service = WorkflowServiceStubs.newServiceStubs(
                WorkflowServiceStubsOptions.newBuilder()
                        .setTarget(target)
                        .build());
        WorkflowClient client = WorkflowClient.newInstance(service);

        SayHelloWorkflow sayHelloWorkflow = client.newWorkflowStub(
                SayHelloWorkflow.class,
                WorkflowOptions.newBuilder()
                        .setTaskQueue("my-task-queue")
                        .setWorkflowId("say-hello-workflow")
                        .build());

        // asynchronous workflow execution
        WorkflowExecution execution = WorkflowClient.start(sayHelloWorkflow::sayHello, new SayHelloRequest("Trung Vo", shouldFail));
        System.out.println("Started: " + execution.getWorkflowId() + ", with run ID: " + execution.getRunId());
        System.out.println("1. Greeting status query: " + sayHelloWorkflow.getGreetingStatus());
        sayHelloWorkflow.setGreetingStatus("Greeting is forced to be in progress now!");
        pauseBeforeQueryAgain(3000);
        System.out.println("2. Greeting status query: " + sayHelloWorkflow.getGreetingStatus());
        pauseBeforeQueryAgain(8000);
        System.out.println("3. Greeting status query: " + sayHelloWorkflow.getGreetingStatus());

        CountDownLatch shutdownLatch = new CountDownLatch(1);

        CompletableFuture<String> resultFuture = WorkflowStub.fromTyped(sayHelloWorkflow)
                .getResultAsync(String.class);

        resultFuture.whenComplete((result, error) -> {
            System.out.println("4. Greeting status query: " + sayHelloWorkflow.getGreetingStatus());
            if (error != null) {
                System.err.println("SayHelloWorkflow failed: ");
                error.printStackTrace();
            } else {
                System.out.println("SayHelloWorkflow completed: " + result);
            }
            cleanUp(service);
            shutdownLatch.countDown();
        });

        try {
            shutdownLatch.await();
        } catch (InterruptedException e) {
            e.printStackTrace();
        }
    }

    static String resolveTemporalTarget() {
        return System.getProperty("temporalTarget");
    }

    static void pauseBeforeQueryAgain(long milis) {
        try {
            Thread.sleep(milis);
        } catch (InterruptedException e) {
            Thread.currentThread().interrupt();
            throw new RuntimeException("Interrupted while waiting to query the workflow", e);
        }
    }

    static void cleanUp(WorkflowServiceStubs service) {
        System.out.println("Shutting down Temporal service...");
        service.shutdown();
        service.awaitTermination(10, java.util.concurrent.TimeUnit.SECONDS);
    }

}
